source "https://rubygems.org"
ruby "2.2.6"

detected_ruby_version = Gem::Version.new(RUBY_VERSION.dup)
required_ruby_version = Gem::Version.new("2.2.6") # minimum supported version

if detected_ruby_version < required_ruby_version
  fail "RUBY_VERSION must be at least #{required_ruby_version}, " \
       "detected RUBY_VERSION #{RUBY_VERSION}"
end

gem "benchmark-ips"
gem "minitest"
gem "rake"